language: node_js
node_js:
  - "12"
sudo: false
dist: trusty
notifications:
  email: false
cache:
  directories:
    - ./node_modules
install:
  - npm install
#script:
  - ng lint
  #- ng build --prod --base-href https://dxree.github.io/MyCargonaut/
  #- cp dist/mycargonaut/index.html dist/mycargonaut/404.html
  #- ng test --watch=false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/mycargonaut
  keep_history: true
  on:
    branch: main
