language: node_js
node_js:
  - "12"
sudo: false
dist: trusty
notifications:
  email: false
cache:
  directories:
    - ./node_modules
install:
  - npm install
script:
  - ng lint
  - npm run build:ssr
  - ng test --watch=false
